export const Province = [
  { id: 57, name: "An Giang", slug: "an-giang" },
  { id: 49, name: "Bà Rịa - Vũng Tàu", slug: "ba-ria-vung-tau" },
  { id: 62, name: "Bạc Liêu", slug: "bac-lieu" },
  { id: 15, name: "Bắc Giang", slug: "bac-giang" },
  { id: 4, name: "Bắc Kạn", slug: "bac-kan" },
  { id: 18, name: "Bắc Ninh", slug: "bac-ninh" },
  { id: 53, name: "Bến Tre", slug: "ben-tre" },
  { id: 47, name: "Bình Dương", slug: "binh-duong" },
  { id: 35, name: "Bình Định", slug: "binh-dinh" },
  { id: 45, name: "Bình Phước", slug: "binh-phuoc" },
  { id: 39, name: "Bình Thuận", slug: "binh-thuan" },
  { id: 63, name: "Cà Mau", slug: "ca-mau" },
  { id: 3, name: "Cao Bằng", slug: "cao-bang" },
  { id: 59, name: "Cần Thơ", slug: "can-tho" },
  { id: 32, name: "Đà Nẵng", slug: "da-nang" },
  { id: 42, name: "Đắk Lắk", slug: "dak-lak" },
  { id: 43, name: "Đắk Nông", slug: "dac-nong" },
  { id: 48, name: "Đồng Nai", slug: "dong-nai" },
  { id: 56, name: "Đồng Tháp", slug: "dong-thap" },
  { id: 7, name: "Điện Biên", slug: "dien-bien" },
  { id: 41, name: "Gia Lai", slug: "gia-lai" },
  { id: 2, name: "Hà Giang", slug: "ha-giang" },
  { id: 23, name: "Hà Nam", slug: "ha-nam" },
  { id: 1, name: "Hà Nội", slug: "ha-noi" },
  { id: 28, name: "Hà Tĩnh", slug: "ha-tinh" },
  { id: 20, name: "Hải Dương", slug: "hai-duong" },
  { id: 27, name: "Hải Phòng", slug: "hai-phong" },
  { id: 11, name: "Hòa Bình", slug: "hoa-binh" },
  { id: 60, name: "Hậu Giang", slug: "hau-giang" },
  { id: 21, name: "Hưng Yên", slug: "hung-yen" },
  { id: 50, name: "Thành phố Hồ Chí Minh", slug: "ho-chi-minh-city" },
  { id: 37, name: "Khánh Hòa", slug: "khanh-hoa" },
  { id: 58, name: "Kiên Giang", slug: "kien-giang" },
  { id: 40, name: "Kon Tum", slug: "kon-tum" },
  { id: 8, name: "Lai Châu", slug: "lai-chau" },
  { id: 6, name: "Lào Cai", slug: "lao-cai" },
  { id: 13, name: "Lạng Sơn", slug: "lang-son" },
  { id: 44, name: "Lâm Đồng", slug: "lam-dong" },
  { id: 51, name: "Long An", slug: "long-an" },
  { id: 24, name: "Nam Định", slug: "nam-dinh" },
  { id: 27, name: "Nghệ An", slug: "nghe-an" },
  { id: 25, name: "Ninh Bình", slug: "ninh-binh" },
  { id: 38, name: "Ninh Thuận", slug: "ninh-thuan" },
  { id: 16, name: "Phú Thọ", slug: "phu-tho" },
  { id: 36, name: "Phú Yên", slug: "phu-yen" },
  { id: 29, name: "Quảng Bình", slug: "quang-binh" },
  { id: 33, name: "Quảng Nam", slug: "quang-nam" },
  { id: 34, name: "Quảng Ngãi", slug: "quang-ngai" },
  { id: 14, name: "Quảng Ninh", slug: "quang-ninh" },
  { id: 30, name: "Quảng Trị", slug: "quang-tri" },
  { id: 61, name: "Sóc Trăng", slug: "soc-trang" },
  { id: 9, name: "Sơn La", slug: "son-la" },
  { id: 46, name: "Tây Ninh", slug: "tay-ninh" },
  { id: 22, name: "Thái Bình", slug: "thai-binh" },
  { id: 12, name: "Thái Nguyên", slug: "thai-nguyen" },
  { id: 26, name: "Thanh Hóa", slug: "thanhhoa" },
  { id: 31, name: "Thừa Thiên  Huế", slug: "thua-thien-hue" },
  { id: 52, name: "Tiền Giang", slug: "tien-giang" },
  { id: 54, name: "Trà Vinh", slug: "tra-vinh" },
  { id: 5, name: "Tuyên Quang", slug: "tuyen-quang" },
  { id: 55, name: "Vĩnh Long", slug: "vinh-long" },
  { id: 17, name: "Vĩnh Phúc", slug: "vinh-phuc" },
  { id: 10, name: "Yên Bái", slug: "yen-bai" }
]

